---
driver:
  name: vagrant
  network:
  # - ["forwarded_port", {guest: 8001, host: 7070, auto_correct: true}]
  # - ["forwarded_port", {guest: 8081, host: 7071, auto_correct: true}]
  - ["forwarded_port", {guest: 80, host: 7000, auto_correct: true}]
  - ["forwarded_port", {guest: 8900, host: 8900, auto_correct: true}]
  synced_folders:
    - ["~/", "/vagrant", "create: true"]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default-nginx
    data_bags_path: "../../data_bags"
    run_list:
      # - recipe[ge_external_certs::default]
      - recipe[aws_elb_webserver::create_user]
      - recipe[aws_elb_webserver::deploy_site]
      - recipe[aws_elb_webserver::configure_nginx]
    attributes:
  - name: default-httpd-1
    data_bags_path: "../../data_bags"
    run_list:
      # - recipe[ge_external_certs::default]
      - recipe[aws_elb_webserver::create_user]
      - recipe[aws_elb_webserver::deploy_site]
      - recipe[aws_elb_webserver::configure_httpd]
    attributes:
  - name: default-httpd-2
    data_bags_path: "../../data_bags"
    run_list:
      # - recipe[ge_external_certs::default]
      - recipe[aws_elb_webserver::create_user]
      - recipe[aws_elb_webserver::deploy_site]
      - recipe[aws_elb_webserver::configure_httpd]
    attributes:
