---
driver:
  name: ec2
  region: us-west-2
  availability_zone: c
  aws_ssh_key_id: devops_rsa
  instance_type: t2.micro
  subnet_id: subnet-d3957888
  # subnet_id: subnet-6b470a0f
  security_group_ids: ["sg-a57fdbde"]
  shared_credentials_profile: personal
  require_chef_omnibus: true
  # associate_public_ip: true
  tags:
    Name: aws_elb_webserver
    app: commons
    role: app
    env: prod
    CreatedBy: Josh.Schneider


provisioner:
  name: chef_zero

transport:
  # username: ubuntu
  ssh_key: ~/.ssh/devops_rsa
  connection_timeout: 120
  connection_retries: 20

block_device_mappings:
  delete_on_termination: true

platforms:
  - name: ubuntu
    driver:
      image_id: ami-5e63d13e # ami from instructions

suites:
  - name: nginx
    data_bags_path: "../../data_bags"
    run_list:
      # - recipe[ge_external_certs::default]
      - recipe[aws_elb_webserver::create_user]
      - recipe[aws_elb_webserver::deploy_site]
      - recipe[aws_elb_webserver::configure_nginx]
    attributes:
  - name: httpd-1
    data_bags_path: "../../data_bags"
    run_list:
      # - recipe[ge_external_certs::default]
      - recipe[aws_elb_webserver::create_user]
      - recipe[aws_elb_webserver::deploy_site]
      - recipe[aws_elb_webserver::configure_httpd]
    attributes:
  - name: httpd-2
    data_bags_path: "../../data_bags"
    run_list:
      # - recipe[ge_external_certs::default]
      - recipe[aws_elb_webserver::create_user]
      - recipe[aws_elb_webserver::deploy_site]
      - recipe[aws_elb_webserver::configure_httpd]
    attributes:
  - name: elb
    data_bags_path: "../../data_bags"
    run_list:
      # - recipe[ge_external_certs::default]
      - recipe[aws_elb_webserver::create_elb]
    attributes:
